### ISSUE TITLE
[cryptoget] Github Action codecov running in CI/CD

### ISSUE THREAD

**Issue by BeauBouchard** [Crucible-Standard/cryptoget#131]
Previously the last codecov implementation was done with `master` branch and not the most recent `main` 

Also Github/actions updated and the codecov library updated with new ways to run it since the "incident" ... 

We want to update the implementation so the repo is automatically reporting coverage changes to PR, as well as pushing that coverage to the codecov reporting page. 

### Tasks 

* [x] CI step for CodeCov Reporting upload
* [ ] Codecov branch updated to main
* [ ] update readme.md
